import fs from 'fs';
import path from 'path';
import type { QuestSeedItem } from './questTypes';

const DATA_DIR = path.join(process.cwd(), '..', 'Garden-of-the-Self', 'data');
export const QUESTS_JSONL = path.join(DATA_DIR, 'quests.jsonl');
export const QUESTS_SEED_TS = path.join(DATA_DIR, 'quests-seed.ts');

export function readQuests(): QuestSeedItem[] {
  try {
    const content = fs.readFileSync(QUESTS_JSONL, 'utf-8');
    return content
      .split('\n')
      .filter((line) => line.trim())
      .map((line) => JSON.parse(line) as QuestSeedItem);
  } catch {
    return [];
  }
}

export function appendQuest(quest: QuestSeedItem): void {
  fs.appendFileSync(QUESTS_JSONL, JSON.stringify(quest) + '\n');
}

export function regenerateSeedTs(quests: QuestSeedItem[]): void {
  const questsJson = JSON.stringify(quests, null, 2);
  const tsContent = `// AUTO-GENERATED by Quest Maker — edit quests.jsonl, not this file directly.
// Open Quest Maker (npm run dev in Quest-Maker/) and Save a quest to update this file.

export type QuestSeedItem = {
  prompt: string;
  virtues: Record<string, number>;
  duration: QuestDuration;
};

export type QuestDuration = 'Long' | 'Medium' | 'Short';

export const questDurationOrder: QuestDuration[] = ['Long', 'Medium', 'Short'];

export const questsSeed: QuestSeedItem[] = ${questsJson};
`;
  fs.writeFileSync(QUESTS_SEED_TS, tsContent);
}
